export const FORGOT_PASSWORD = 'Quên mật khẩu'
export const LOG_IN = 'Đăng nhập'
export const REGISTER = 'Đăng ký'
export const CANCEL = 'Hủy'
export const SAVE = 'Lưu';
export const SEND = 'Send';
export const MY_WALLET = 'Danh sách ví';
export const WALLET_ID = 'Địa chỉ ví:';
export const WALLET_NAME = 'Tên ví:';
export const ACTIVE_WORKERS = 'Active workers:';
export const UNPAID_BALANCE = 'Unpaid Balance:';
export const WALLET_BALANCE = 'Wallet Balance:';
export const MY_ACCOUNT = 'Tài khoản của tôi';
export const CHANGE_PASSWORD = 'Đổi mật khẩu';
export const LOG_OUT = 'Thoát';
export const PERIOUS = 'Perious';
export const HOUR = 'Giờ';
export const DAY = 'Ngày';
export const WEEK = 'Tuần';
export const MONTH ='Tháng';
export const YEAR = 'Năm';
export const ETH = 'ETH';
export const BTC = 'BTC';
export const USD = 'USD';
export const RELOAD = 'Làm mới';
export const DELETE_ALL = 'Xoá';
export const DISCONNECT = 'Mất kết nối';
export const TEMP = 'Temp(°C)';
export const FAN_SPEED = 'Fan(%)';
export const HASH_RATE = 'Hashrate';
export const TOTAL_HASH_RATE = 'Total hashrate(Mh/s): ';
export const GPU = 'GPU';
export const ADD_NEW_WALLET = 'Add new wallet ID';
export const EDIT_WALLET = 'Update wallet ID';
export const CREATE_ACCOUNT_LABEL='Đăng kí tài khoản';
export const VALID_TOKEN_EMAIL = 'Star mining đã gửi một mã xác nhận đến email của bạn.\nVui lòng nhập mã xác nhận trong email để tiếp tục.';
export const SHOP = 'Shop';
export const COINSPRICE='Thị trường coins';
export const RANKING = 'Xếp hạng:';
export const TOTAL_POINT = 'Điểm tích lũy:';
export const USED_POINT = 'Điểm đã dùng:';
export const OK = 'Đồng ý';
export const UPDATE_ACCOUNT_TITLE = 'Cập nhật tài khoản';
export const UPDATE_ACCOUNT_SUBTITLE = 'Bạn có muốn thay đổi thông tin tài khoản?';
export const SOCIAL_LOGIN_WITH_BTN = 'Đăng nhập với';
export const SOCIAL_FB_LOGIN = 'Facebook';