export const ADD_ALL_ITEM_TO_LIST_WALLET = 'ADD_ALL_ITEM_TO_LIST_WALLET';
export const ADD_ITEM_TO_LIST_WALLET = 'ADD_ITEM_TO_LIST_WALLET';
export const DELETE_ITEM_WALLET = 'DELETE_ITEM_WALLET';

// coins price
export const ADD_NEW_DATA_COINS_PRICE = 'ADD_NEW_DATA_COINS_PRICE';

// shop
export const ADD_NEW_DATA_PRODUCTS = 'ADD_NEW_DATA_PRODUCTS';
