const DRAWER_BACKGROUND = '#E0E0E0';
const MAIN_BACKGROUND = 'rgba(30, 30, 30, 1)';

const MAIN_TEXT_COLOR = 'rgba(255, 255, 255, 1)';
const HEADER_TEXT_COLOR = 'black';
const ORANGE_TEXT_COLOR = 'rgba(177, 106, 22, 1)';
const YELLOW_TEXT_COLOR = '#FFFF00';

const MAIN_BUTTON_BACKGROUND = 'rgba(0, 0, 28, 1)';
const MAIN_HEADER_BACKGROUND = 'rgba(255, 255, 255, 1)';
const TRANSPARENT_COLOR = 'rgba(0, 0, 0, 0)';
// button
const BTN_LOGIN_BG_COLOR = '#04B6FE';
const BTN_REGISTER_BG_COLOR = '#0E999E';
const BTN_CANCEL_BG_COLOR = '#B71C1C';
const BTN_SOCIAL_FB_BG_COLOR = '#3b5998';

// input 
const INPUT_BORDER_COLOR = 'rgba(255, 255, 255, 1)';
const LABEL_COLOR_PURPLE = '#4A148C';

// border color
const BORDER_WORKER_COLOR = 'grey';

export {
    DRAWER_BACKGROUND,
    MAIN_BACKGROUND,

    MAIN_TEXT_COLOR,
    HEADER_TEXT_COLOR,
    ORANGE_TEXT_COLOR,
    YELLOW_TEXT_COLOR,

    MAIN_BUTTON_BACKGROUND,
    MAIN_HEADER_BACKGROUND,

    BTN_LOGIN_BG_COLOR,
    BTN_REGISTER_BG_COLOR,
    BTN_CANCEL_BG_COLOR,
    BTN_SOCIAL_FB_BG_COLOR,

    INPUT_BORDER_COLOR,

    TRANSPARENT_COLOR,

    BORDER_WORKER_COLOR,

    LABEL_COLOR_PURPLE
}