module.exports._ON_ARDUINO_CONNECTION = '_ON_ARDUINO_CONNECTION';

module.exports._ON_ADMIN_RECEIVE_LIST_ARDUINO = '_ON_ADMIN_RECEIVE_LIST_ARDUINO';
module.exports._EMIT_ADMIN_REQUEST_LIST_ARDUINO = '_EMIT_ADMIN_REQUEST_LIST_ARDUINO';