export const SELECT_PRODUCT_TYPE = 'SELECT_PRODUCT_TYPE';
export const ADD_PRODUCT_TO_LIST = 'ADD_PRODUCT_TO_LIST';
export const REMOVE_PRODUCT_FROM_LIST = 'REMOVE_PRODUCT_FROM_LIST';
export const INIT_PRODUCT_TYPE = 'INIT_PRODUCT_TYPE';
export const INIT_MESSAGE_CLOSE_MODAL = 'INIT_MESSAGE_CLOSE_MODAL';