export const INIT_DATA_PRODUCT_TYPE = 'INIT_DATA_PRODUCT_TYPE';
export const INIT_DATA_PRODUCT_BUILDPC = 'INIT_DATA_PRODUCT_BUILDPC';


// action app
export const TOOGLE_MODAL_CHOOSE_PRODUCT = 'TOOGLE_MODAL_CHOOSE_PRODUCT';
export const SET_VALUE_PRODUCT_TYPE = 'SET_VALUE_PRODUCT_TYPE';